DROP TABLE IF EXISTS university, department, professor, course, section, resource;

CREATE TABLE university(
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(127) NOT NULL,
  Location VARCHAR(127) NOT NULL
);

CREATE TABLE department(
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(127) NOT NULL,
  U_ID INT NOT NULL,
  FOREIGN KEY (U_ID) REFERENCES university(ID)
);

CREATE TABLE professor(
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  D_ID INT NOT NULL,
  Birth_Date DATE,
  Name VARCHAR(63) NOT NULL,
  Degree VARCHAR(31),
  Alma_Mater VARCHAR(127),
  Tenured BOOL,
  Start_Date DATE,
  FOREIGN KEY (D_ID) REFERENCES department(ID)
);

CREATE TABLE course(
  ID INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(127) NOT NULL,
  Number INT NOT NULL,
  D_ID INT NOT NULL,
  FOREIGN KEY (D_ID) REFERENCES department(ID)
);

CREATE TABLE section(

  ID INT NOT NULL PRIMARY KEY,
  Year VARCHAR(15) NOT NULL,
  Semester VARCHAR(15) NOT NULL,
  P_ID INT NOT NULL,
  C_ID INT NOT NULL,
  FOREIGN KEY (P_ID) REFERENCES professor(ID),
  FOREIGN KEY (C_ID) REFERENCES course(ID)
);

CREATE TABLE resource(

  ID int NOT NULL PRIMARY KEY ,
  Description CLOB(1K),
  Path CLOB(1K) NOT NULL,
  Upload_Date DATE NOT NULL,
  S_ID int NOT NULL,
  FOREIGN KEY (S_ID) REFERENCES section(ID)
);
